package com.invoicely.web;

import com.invoicely.domain.Role;
import com.invoicely.domain.User;
import java.time.Instant;

/**
 * What {@code POST /team} returns: everything {@link StaffResponse} shows,
 * plus the temporary password the owner needs to pass along.
 *
 * <p>This is the only place that password is ever visible in plain text. Once
 * this response is sent it cannot be recovered — only its BCrypt hash is
 * stored, generated by {@link com.invoicely.security.TemporaryPasswords} and
 * {@link org.springframework.security.crypto.password.PasswordEncoder} in
 * {@link TeamService#create}. The fields are duplicated from
 * {@code StaffResponse} rather than nesting one inside the other, so the two
 * response bodies stay flat and equally easy to read off the wire.
 */
public record CreatedStaffResponse(
        Long id,
        String name,
        String email,
        Role role,
        boolean active,
        Instant createdAt,
        String temporaryPassword) {

    public static CreatedStaffResponse from(User user, String temporaryPassword) {
        return new CreatedStaffResponse(
                user.getId(),
                user.getName(),
                user.getEmail(),
                user.getRole(),
                user.isActive(),
                user.getCreatedAt(),
                temporaryPassword);
    }
}
